igtl::ImageMetaElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::ImageMetaElement Class Reference
#include <igtlImageMetaMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef ImageMetaElement Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
const char * GetDeviceName ()
const char * GetModality ()
const char * GetName ()
virtual const char * GetNameOfClass () const
const char * GetPatientID ()
const char * GetPatientName ()
virtual int GetReferenceCount () const
igtlUint8 GetScalarType ()
void GetSize (igtlUint16 *size)
void GetSize (igtlUint16 &si, igtlUint16 &sj, igtlUint16 &sk)
void GetTimeStamp (igtl::TimeStamp::Pointer &time)
igtlNewMacro (igtl::ImageMetaElement)
igtlTypeMacro (igtl::ImageMetaElement, igtl::Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
int SetDeviceName (const char *devname)
int SetModality (const char *modality)
int SetName (const char *name)
int SetPatientID (const char *patid)
int SetPatientName (const char *patname)
virtual void SetReferenceCount (int)
void SetScalarType (igtlUint8 type)
void SetSize (igtlUint16 size[3])
void SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
void SetTimeStamp (igtl::TimeStamp::Pointer &time)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
ImageMetaElement ()
virtual void PrintSelf (std::ostream &os) const
~ImageMetaElement ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
std::string m_DeviceName
std::string m_Modality
std::string m_Name
std::string m_PatientID
std::string m_PatientName
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_ScalarType
igtlUint16 m_Size [3]
TimeStamp::Pointer m_TimeStamp
Detailed Description
A class to manage meta data of images.
Definition at line 32 of file igtlImageMetaMessage.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::ImageMetaElement::ConstPointer
Definition at line 38 of file igtlImageMetaMessage.h.
typedef SmartPointer<Self> igtl::ImageMetaElement::Pointer
Definition at line 37 of file igtlImageMetaMessage.h.
typedef ImageMetaElement igtl::ImageMetaElement::Self
Definition at line 35 of file igtlImageMetaMessage.h.
typedef Object igtl::ImageMetaElement::Superclass
Definition at line 36 of file igtlImageMetaMessage.h.
Constructor & Destructor Documentation
igtl::ImageMetaElement::ImageMetaElement () protected
igtl::ImageMetaElement::~ImageMetaElement () protected
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
const char* igtl::ImageMetaElement::GetDeviceName () inline
Gets the device name (message name).
Definition at line 56 of file igtlImageMetaMessage.h.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
const char* igtl::ImageMetaElement::GetModality () inline
Gets the name of the image modality.
Definition at line 63 of file igtlImageMetaMessage.h.
const char* igtl::ImageMetaElement::GetName () inline
Gets the image name/description.
Definition at line 49 of file igtlImageMetaMessage.h.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
const char* igtl::ImageMetaElement::GetPatientID () inline
Gets the patient ID.
Definition at line 75 of file igtlImageMetaMessage.h.
const char* igtl::ImageMetaElement::GetPatientName () inline
Gets the patient name.
Definition at line 69 of file igtlImageMetaMessage.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
igtlUint8 igtl::ImageMetaElement::GetScalarType ()
Gets the scalar type of the image.
void igtl::ImageMetaElement::GetSize (igtlUint16 * size)
Gets the size of the image using an array containing the numbers of voxels in i, j, and k directions.
void igtl::ImageMetaElement::GetSize (igtlUint16 & si, igtlUint16 & sj, igtlUint16 & sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
void igtl::ImageMetaElement::GetTimeStamp (igtl::TimeStamp::Pointer & time)
Gets the scan time for the image.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::ImageMetaElement::igtlNewMacro (igtl::ImageMetaElement)
igtl::ImageMetaElement::igtlTypeMacro (igtl::ImageMetaElement , igtl::Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
int igtl::ImageMetaElement::SetDeviceName (const char * devname)
Sets the device name (message name). The string 'devname' must not exceed 20 characters.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
int igtl::ImageMetaElement::SetModality (const char * modality)
Sets the name of the image modality (e.g. CT, MRI). The string 'modality' must not exceed 32 characters.
int igtl::ImageMetaElement::SetName (const char * name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
int igtl::ImageMetaElement::SetPatientID (const char * patid)
Sets the patient ID. The string 'patid' must not exceed 64 characters.
int igtl::ImageMetaElement::SetPatientName (const char * patname)
Sets the patient name. The string 'patname' must not exceed 64 characters.
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
void igtl::ImageMetaElement::SetScalarType (igtlUint8 type)
Sets the scalar type of the image.
void igtl::ImageMetaElement::SetSize (igtlUint16 size[3])
Sets the size of the image by an array containing the numbers of voxels in i, j, and k directions.
void igtl::ImageMetaElement::SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
void igtl::ImageMetaElement::SetTimeStamp (igtl::TimeStamp::Pointer & time)
Sets the scan time for the image.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
std::string igtl::ImageMetaElement::m_DeviceName protected
device name to query the IMAGE and COLORT
Definition at line 113 of file igtlImageMetaMessage.h.
std::string igtl::ImageMetaElement::m_Modality protected
modality name (<= 32 bytes)
Definition at line 116 of file igtlImageMetaMessage.h.
std::string igtl::ImageMetaElement::m_Name protected
name / description (<= 64 bytes)
Definition at line 110 of file igtlImageMetaMessage.h.
std::string igtl::ImageMetaElement::m_PatientID protected
patient ID (MRN etc.) (<= 64 bytes)
Definition at line 122 of file igtlImageMetaMessage.h.
std::string igtl::ImageMetaElement::m_PatientName protected
patient name (<= 64 bytes)
Definition at line 119 of file igtlImageMetaMessage.h.
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
igtlUint8 igtl::ImageMetaElement::m_ScalarType protected
scalar type. see scalar_type in IMAGE message
Definition at line 131 of file igtlImageMetaMessage.h.
igtlUint16 igtl::ImageMetaElement::m_Size[3] protected
entire image volume size
Definition at line 128 of file igtlImageMetaMessage.h.
TimeStamp::Pointer igtl::ImageMetaElement::m_TimeStamp protected
scan time
Definition at line 125 of file igtlImageMetaMessage.h.
The documentation for this class was generated from the following file:
igtlImageMetaMessage.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012