igtl::TrajectoryElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::TrajectoryElement Class Reference
#include <igtlTrajectoryMessage.h>
Public Types
enum {
TYPE_ENTRY_ONLY = 1,
TYPE_TARGET_ONLY = 2,
TYPE_ENTRY_TARGET = 3
}
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef TrajectoryElement Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
void GetEntryPosition (igtlFloat32 *position)
void GetEntryPosition (igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
const char * GetGroupName ()
const char * GetName ()
virtual const char * GetNameOfClass () const
const char * GetOwner ()
igtlFloat32 GetRadius ()
virtual int GetReferenceCount () const
void GetRGBA (igtlUint8 *rgba)
void GetRGBA (igtlUint8 &r, igtlUint8 &g, igtlUint8 &b, igtlUint8 &a)
void GetTargetPosition (igtlFloat32 *position)
void GetTargetPosition (igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
igtlUint8 GetType ()
igtlNewMacro (igtl::TrajectoryElement)
igtlTypeMacro (igtl::TrajectoryElement, igtl::Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
void SetEntryPosition (igtlFloat32 position[3])
void SetEntryPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
int SetGroupName (const char *grpname)
int SetName (const char *name)
int SetOwner (const char *owner)
void SetRadius (igtlFloat32 radius)
virtual void SetReferenceCount (int)
void SetRGBA (igtlUint8 rgba[4])
void SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
void SetTargetPosition (igtlFloat32 position[3])
void SetTargetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
int SetType (igtlUint8 type)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
virtual void PrintSelf (std::ostream &os) const
TrajectoryElement ()
~TrajectoryElement ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
igtlFloat32 m_EntryPosition [3]
std::string m_GroupName
std::string m_Name
std::string m_Owner
igtlFloat32 m_Radius
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_RGBA [4]
igtlFloat32 m_TargetPosition [3]
igtlUint8 m_Type
Detailed Description
TrajectoryElement class is used to manage a trajectory in TrajectoryMessage class.
Definition at line 32 of file igtlTrajectoryMessage.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::TrajectoryElement::ConstPointer
Definition at line 38 of file igtlTrajectoryMessage.h.
typedef SmartPointer<Self> igtl::TrajectoryElement::Pointer
Definition at line 37 of file igtlTrajectoryMessage.h.
typedef TrajectoryElement igtl::TrajectoryElement::Self
Definition at line 35 of file igtlTrajectoryMessage.h.
typedef Object igtl::TrajectoryElement::Superclass
Definition at line 36 of file igtlTrajectoryMessage.h.
Member Enumeration Documentation
anonymous enum
Types of trajectory.
Enumerator
TYPE_ENTRY_ONLY
TYPE_TARGET_ONLY
TYPE_ENTRY_TARGET
Definition at line 44 of file igtlTrajectoryMessage.h.
Constructor & Destructor Documentation
igtl::TrajectoryElement::TrajectoryElement () protected
igtl::TrajectoryElement::~TrajectoryElement () protected
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
void igtl::TrajectoryElement::GetEntryPosition (igtlFloat32 * position)
Sets the entry position using an array of x, y, and z coordinates.
void igtl::TrajectoryElement::GetEntryPosition (igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the entry position.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
const char* igtl::TrajectoryElement::GetGroupName () inline
Gets the group name.
Definition at line 62 of file igtlTrajectoryMessage.h.
const char* igtl::TrajectoryElement::GetName () inline
Gets the name of the trajectory.
Definition at line 56 of file igtlTrajectoryMessage.h.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
const char* igtl::TrajectoryElement::GetOwner () inline
Gets the owner of the trajectory.
Definition at line 115 of file igtlTrajectoryMessage.h.
igtlFloat32 igtl::TrajectoryElement::GetRadius () inline
Gets the radius.
Definition at line 109 of file igtlTrajectoryMessage.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
void igtl::TrajectoryElement::GetRGBA (igtlUint8 * rgba)
Gets the color of the trajectory. An array of r, g, b and alpha is stored in 'rgba'.
void igtl::TrajectoryElement::GetRGBA (igtlUint8 & r, igtlUint8 & g, igtlUint8 & b, igtlUint8 & a)
Gets the color of the trajectory.
void igtl::TrajectoryElement::GetTargetPosition (igtlFloat32 * position)
Gets the target position. Stores an array of x, y, and z coordinates in 'position'.
void igtl::TrajectoryElement::GetTargetPosition (igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the target position.
igtlUint8 igtl::TrajectoryElement::GetType () inline
Gets the trajectory type. The returned value is either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
Definition at line 67 of file igtlTrajectoryMessage.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::TrajectoryElement::igtlNewMacro (igtl::TrajectoryElement)
igtl::TrajectoryElement::igtlTypeMacro (igtl::TrajectoryElement , igtl::Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
void igtl::TrajectoryElement::SetEntryPosition (igtlFloat32 position[3])
Sets the entry position using an array.
void igtl::TrajectoryElement::SetEntryPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the entry position.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
int igtl::TrajectoryElement::SetGroupName (const char * grpname)
Sets the group name e.g. "Trajectory".
int igtl::TrajectoryElement::SetName (const char * name)
Sets the name of the trajectory.
int igtl::TrajectoryElement::SetOwner (const char * owner)
Sets the owner of the trajectory. 'owner' must be a name of image.
void igtl::TrajectoryElement::SetRadius (igtlFloat32 radius) inline
Sets the radius.
Definition at line 106 of file igtlTrajectoryMessage.h.
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
void igtl::TrajectoryElement::SetRGBA (igtlUint8 rgba[4])
Sets the color of the trajectory using an array of r, g, b and alpha.
void igtl::TrajectoryElement::SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the trajectory by r, g, b and alpha.
void igtl::TrajectoryElement::SetTargetPosition (igtlFloat32 position[3])
Sets the target position using an array of x, y, and z coordinates.
void igtl::TrajectoryElement::SetTargetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the target position.
int igtl::TrajectoryElement::SetType (igtlUint8 type)
Sets the trajectory type. 'type' must be either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
igtlFloat32 igtl::TrajectoryElement::m_EntryPosition[3] protected
Coordinate of the entry point.
Definition at line 136 of file igtlTrajectoryMessage.h.
std::string igtl::TrajectoryElement::m_GroupName protected
Can be "Labeled Trajectory", "Landmark", Fiducial", ...
Definition at line 127 of file igtlTrajectoryMessage.h.
std::string igtl::TrajectoryElement::m_Name protected
name / description (< 64 bytes)
Definition at line 124 of file igtlTrajectoryMessage.h.
std::string igtl::TrajectoryElement::m_Owner protected
Device name of the ower image.
Definition at line 145 of file igtlTrajectoryMessage.h.
igtlFloat32 igtl::TrajectoryElement::m_Radius protected
Radius of the trajectory. Can be 0.
Definition at line 142 of file igtlTrajectoryMessage.h.
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
igtlUint8 igtl::TrajectoryElement::m_RGBA[4] protected
Color in R/G/B/A.
Definition at line 133 of file igtlTrajectoryMessage.h.
igtlFloat32 igtl::TrajectoryElement::m_TargetPosition[3] protected
Coordinate of the target point.
Definition at line 139 of file igtlTrajectoryMessage.h.
igtlUint8 igtl::TrajectoryElement::m_Type protected
Trajectory type (see TYPE_* constants)
Definition at line 130 of file igtlTrajectoryMessage.h.
The documentation for this class was generated from the following file:
igtlTrajectoryMessage.h
Generated at Wed Sep 3 2014 08:12:39 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012