igtl::PolyDataCellArray Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::PolyDataCellArray Class Reference
#include <igtlPolyDataMessage.h>
Public Types
enum { NULL_POINT = 0xFFFFFFFF }
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef PolyDataCellArray Self
typedef Object Superclass
Public Member Functions
void AddCell (int n, igtlUint32 *cell)
void AddCell (std::list< igtlUint32 > cell)
void Clear ()
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int GetCell (unsigned int id, igtlUint32 *cell)
int GetCell (unsigned int id, std::list< igtlUint32 > &cell)
igtlUint32 GetCellSize (unsigned int id)
bool GetDebug () const
virtual const char * GetNameOfClass () const
igtlUint32 GetNumberOfCells ()
virtual int GetReferenceCount () const
igtlUint32 GetTotalSize ()
igtlNewMacro (igtl::PolyDataCellArray)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::PolyDataCellArray, igtl::Object)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
PolyDataCellArray ()
virtual void PrintSelf (std::ostream &os) const
~PolyDataCellArray ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 110 of file igtlPolyDataMessage.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::PolyDataCellArray::ConstPointer
Definition at line 121 of file igtlPolyDataMessage.h.
typedef SmartPointer<Self> igtl::PolyDataCellArray::Pointer
Definition at line 120 of file igtlPolyDataMessage.h.
typedef PolyDataCellArray igtl::PolyDataCellArray::Self
Definition at line 118 of file igtlPolyDataMessage.h.
typedef Object igtl::PolyDataCellArray::Superclass
Definition at line 119 of file igtlPolyDataMessage.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NULL_POINT
Definition at line 113 of file igtlPolyDataMessage.h.
Constructor & Destructor Documentation
igtl::PolyDataCellArray::PolyDataCellArray () protected
igtl::PolyDataCellArray::~PolyDataCellArray () protected
Member Function Documentation
void igtl::PolyDataCellArray::AddCell (int n, igtlUint32 * cell)
Adds an array of cells stored in 'cell'. The number of cells is specified by 'n'.
void igtl::PolyDataCellArray::AddCell (std::list< igtlUint32 > cell)
Adds an array of cells stored in 'cell'.
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
void igtl::PolyDataCellArray::Clear ()
Clears the cell array.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
int igtl::PolyDataCellArray::GetCell (unsigned int id, igtlUint32 * cell)
Gets the cell specified by the 'id'. A list of points in the cell will be stored in the 'cell'. A memory area sufficient to store the points in the cell must be allocated before calling GetCell() function, and specified as 'cell'.
int igtl::PolyDataCellArray::GetCell (unsigned int id, std::list< igtlUint32 > & cell)
Gets the cell specified by the 'id'. A list of points in the cell will be stored in the 'cell'.
igtlUint32 igtl::PolyDataCellArray::GetCellSize (unsigned int id)
Gets the size of the cell specified by 'id'.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
igtlUint32 igtl::PolyDataCellArray::GetNumberOfCells ()
Gets the number of cells in the array.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
igtlUint32 igtl::PolyDataCellArray::GetTotalSize ()
GetTotalSize() returns the total memory size of the cell data array in POLYDATA message. Cell data array is array of cell data, consisting of <number of="" points>=""> and array of <point indecies>="">. Both <number of="" points>=""> and <point indecies>=""> are unsigned 32-bit integer. Consequently, the total size can be calculated by: sizeof(igtlUint32) * (number of points for 0th cell + 1) + (number of points for 1th cell + 1) ... + (number of points for (N-1)th cell + 1). Note that this includes the first igtlUint32 value that specifies the number of points in each cell.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::PolyDataCellArray::igtlNewMacro (igtl::PolyDataCellArray)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
igtl::PolyDataCellArray::igtlTypeMacro (igtl::PolyDataCellArray , igtl::Object)
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
The documentation for this class was generated from the following file:
igtlPolyDataMessage.h
Generated at Wed Sep 3 2014 08:12:39 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012