igtl::Object Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::Object Class Reference
#include <igtlObject.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef Object Self
typedef LightObject Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
Object ()
virtual void PrintSelf (std::ostream &os) const
virtual ~Object ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Base class for most igtl classes.
Object is the second-highest level base class for most igtl objects. It extends the base object functionality of LightObject by implementing callbacks (via object/observer), debug flags/methods, and modification time tracking. Most IGTL classes should be a subclas of Object due to the need to keep track of modified time.
Definition at line 62 of file igtlObject.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::Object::ConstPointer
Reimplemented from igtl::LightObject.
Reimplemented in igtl::PolyDataMessage, igtl::RTSBindMessage, igtl::QuaternionTrackingDataMessage, igtl::TrackingDataMessage, igtl::PolyDataAttribute, igtl::StopBindMessage, igtl::RTSQuaternionTrackingDataMessage, igtl::RTSTrackingDataMessage, igtl::MultiThreader, igtl::MutexLock, igtl::StartBindMessage, igtl::StopQuaternionTrackingDataMessage, igtl::TrajectoryMessage, igtl::StopTrackingDataMessage, igtl::ImageMetaMessage, igtl::LabelMetaMessage, igtl::NDArrayMessage, igtl::PointMessage, igtl::GetBindMessage, igtl::GetTrajectoryMessage, igtl::PolyDataCellArray, igtl::Unit, igtl::GetImageMetaMessage, igtl::StartQuaternionTrackingDataMessage, igtl::GetLabelMetaMessage, igtl::GetPointMessage, igtl::StartTrackingDataMessage, igtl::BindMessage, igtl::FastMutexLock, igtl::ObjectFactoryBase, igtl::ImageMessage2, igtl::Socket, igtl::MessageBase, igtl::PolyDataPointArray, igtl::ColorTableMessage, igtl::ImageMessage, igtl::CreateObjectFunctionBase, igtl::ServerSocket, igtl::ClientSocket, igtl::GetImageMessage2, igtl::PositionMessage, igtl::ImageMetaElement, igtl::LabelMetaElement, igtl::PointElement, igtl::TrajectoryElement, igtl::QuaternionTrackingDataElement, igtl::TrackingDataElement, igtl::BindMessageBase, igtl::SensorMessage, igtl::StringMessage, igtl::TimeStamp, igtl::GetPolyDataMessage, igtl::TransformMessage, igtl::GetColorTableMessage, igtl::GetImageMessage, and igtl::StatusMessage.
Definition at line 69 of file igtlObject.h.
typedef SmartPointer<Self> igtl::Object::Pointer
Reimplemented from igtl::LightObject.
Reimplemented in igtl::PolyDataMessage, igtl::RTSBindMessage, igtl::QuaternionTrackingDataMessage, igtl::TrackingDataMessage, igtl::PolyDataAttribute, igtl::StopBindMessage, igtl::RTSQuaternionTrackingDataMessage, igtl::RTSTrackingDataMessage, igtl::MultiThreader, igtl::MutexLock, igtl::StartBindMessage, igtl::StopQuaternionTrackingDataMessage, igtl::TrajectoryMessage, igtl::StopTrackingDataMessage, igtl::ImageMetaMessage, igtl::LabelMetaMessage, igtl::NDArrayMessage, igtl::PointMessage, igtl::GetBindMessage, igtl::GetTrajectoryMessage, igtl::PolyDataCellArray, igtl::Unit, igtl::GetImageMetaMessage, igtl::StartQuaternionTrackingDataMessage, igtl::GetLabelMetaMessage, igtl::GetPointMessage, igtl::StartTrackingDataMessage, igtl::CreateObjectFunction< T >, igtl::BindMessage, igtl::FastMutexLock, igtl::ObjectFactoryBase, igtl::ImageMessage2, igtl::Socket, igtl::MessageBase, igtl::PolyDataPointArray, igtl::ColorTableMessage, igtl::ImageMessage, igtl::CreateObjectFunctionBase, igtl::ServerSocket, igtl::ClientSocket, igtl::GetImageMessage2, igtl::PositionMessage, igtl::ImageMetaElement, igtl::LabelMetaElement, igtl::PointElement, igtl::TrajectoryElement, igtl::QuaternionTrackingDataElement, igtl::TrackingDataElement, igtl::BindMessageBase, igtl::SensorMessage, igtl::StringMessage, igtl::TimeStamp, igtl::GetPolyDataMessage, igtl::TransformMessage, igtl::GetColorTableMessage, igtl::GetImageMessage, and igtl::StatusMessage.
Definition at line 68 of file igtlObject.h.
typedef Object igtl::Object::Self
Smart pointer typedef support.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::PolyDataMessage, igtl::RTSBindMessage, igtl::QuaternionTrackingDataMessage, igtl::TrackingDataMessage, igtl::PolyDataAttribute, igtl::StopBindMessage, igtl::RTSQuaternionTrackingDataMessage, igtl::RTSTrackingDataMessage, igtl::MultiThreader, igtl::MutexLock, igtl::StartBindMessage, igtl::StopQuaternionTrackingDataMessage, igtl::TrajectoryMessage, igtl::StopTrackingDataMessage, igtl::ImageMetaMessage, igtl::LabelMetaMessage, igtl::NDArrayMessage, igtl::PointMessage, igtl::GetBindMessage, igtl::GetTrajectoryMessage, igtl::PolyDataCellArray, igtl::Unit, igtl::GetImageMetaMessage, igtl::StartQuaternionTrackingDataMessage, igtl::GetLabelMetaMessage, igtl::GetPointMessage, igtl::StartTrackingDataMessage, igtl::CreateObjectFunction< T >, igtl::BindMessage, igtl::FastMutexLock, igtl::ObjectFactoryBase, igtl::ImageMessage2, igtl::Socket, igtl::MessageBase, igtl::PolyDataPointArray, igtl::ColorTableMessage, igtl::ImageMessage, igtl::CreateObjectFunctionBase, igtl::ServerSocket, igtl::ClientSocket, igtl::GetImageMessage2, igtl::PositionMessage, igtl::ImageMetaElement, igtl::LabelMetaElement, igtl::PointElement, igtl::TrajectoryElement, igtl::QuaternionTrackingDataElement, igtl::TrackingDataElement, igtl::BindMessageBase, igtl::SensorMessage, igtl::StringMessage, igtl::TimeStamp, igtl::GetPolyDataMessage, igtl::TransformMessage, igtl::GetColorTableMessage, igtl::GetImageMessage, and igtl::StatusMessage.
Definition at line 66 of file igtlObject.h.
typedef LightObject igtl::Object::Superclass
Reimplemented in igtl::PolyDataMessage, igtl::RTSBindMessage, igtl::QuaternionTrackingDataMessage, igtl::TrackingDataMessage, igtl::PolyDataAttribute, igtl::StopBindMessage, igtl::RTSQuaternionTrackingDataMessage, igtl::RTSTrackingDataMessage, igtl::MultiThreader, igtl::MutexLock, igtl::StartBindMessage, igtl::StopQuaternionTrackingDataMessage, igtl::TrajectoryMessage, igtl::StopTrackingDataMessage, igtl::ImageMetaMessage, igtl::LabelMetaMessage, igtl::NDArrayMessage, igtl::PointMessage, igtl::GetBindMessage, igtl::GetTrajectoryMessage, igtl::PolyDataCellArray, igtl::Unit, igtl::GetImageMetaMessage, igtl::StartQuaternionTrackingDataMessage, igtl::GetLabelMetaMessage, igtl::GetPointMessage, igtl::StartTrackingDataMessage, igtl::BindMessage, igtl::FastMutexLock, igtl::ObjectFactoryBase, igtl::ImageMessage2, igtl::Socket, igtl::MessageBase, igtl::PolyDataPointArray, igtl::ColorTableMessage, igtl::ImageMessage, igtl::CreateObjectFunctionBase, igtl::ServerSocket, igtl::ClientSocket, igtl::GetImageMessage2, igtl::PositionMessage, igtl::ImageMetaElement, igtl::LabelMetaElement, igtl::PointElement, igtl::TrajectoryElement, igtl::QuaternionTrackingDataElement, igtl::TrackingDataElement, igtl::BindMessageBase, igtl::SensorMessage, igtl::StringMessage, igtl::TimeStamp, igtl::GetPolyDataMessage, igtl::TransformMessage, igtl::GetColorTableMessage, igtl::GetImageMessage, and igtl::StatusMessage.
Definition at line 67 of file igtlObject.h.
Constructor & Destructor Documentation
igtl::Object::Object () protected
Allow people to add/remove/invoke observers (callbacks) to any IGTL object. This is an implementation of the subject/observer design pattern. An observer is added by specifying an event to respond to and an igtl::Command to execute. It returns an unsigned long tag which can be used later to remove the event or retrieve the command. The memory for the Command becomes the responsibility of this object, so don't pass the same instance of a command to two different objects Get the command associated with the given tag. NOTE: This returns a pointer to a Command, but it is safe to asign this to a Command::Pointer. Since Command inherits from LightObject, at this point in the code, only a pointer or a reference to the Command can be used. Call Execute on all the Commands observing this event id. Call Execute on all the Commands observing this event id. The actions triggered by this call doesn't modify this object. Remove the observer with this tag value. Remove all observers . Return true if an observer is registered for this event.
Returns:
A reference to this objects MetaDataDictionary.
Warning:
This reference may be changed.
Returns:
A constant reference to this objects MetaDataDictionary.
Set the MetaDataDictionary
virtual igtl::Object::~Object () protected virtual
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 86 of file igtlLightObject.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 112 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 118 of file igtlObject.h.
References SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtl::Object::igtlTypeMacro (Object , LightObject)
Standard part of all igtl objects.
static Pointer igtl::Object::New () static
Method for creation through the object factory.
Reimplemented from igtl::LightObject.
Referenced by igtl::CreateObjectFunction< T >::CreateObject().
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::ServerSocket, igtl::TimeStamp, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by GlobalWarningDisplayOff(), and GlobalWarningDisplayOn().
virtual void igtl::Object::SetReferenceCount (int) virtual
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 133 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 136 of file igtlLightObject.h.
The documentation for this class was generated from the following file:
igtlObject.h
Generated at Tue Dec 25 2012 05:54:31 for OpenIGTLink by 1.8.1.1 written by Dimitri van Heesch, © 1997-2012