igtl::PolyDataPointArray Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::PolyDataPointArray Class Reference
#include <igtlPolyDataMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef std::vector< igtlFloat32 > Point
typedef SmartPointer< Self > Pointer
typedef PolyDataPointArray Self
typedef Object Superclass
Public Member Functions
int AddPoint (igtlFloat32 *point)
int AddPoint (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
void Clear ()
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
int GetNumberOfPoints ()
int GetPoint (unsigned int id, igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
int GetPoint (unsigned int id, igtlFloat32 *point)
virtual int GetReferenceCount () const
igtlNewMacro (igtl::PolyDataPointArray)
igtlTypeMacro (igtl::PolyDataPointArray, igtl::Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
void SetNumberOfPoints (int n)
int SetPoint (unsigned int id, igtlFloat32 *point)
int SetPoint (unsigned int id, igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
PolyDataPointArray ()
virtual void PrintSelf (std::ostream &os) const
~PolyDataPointArray ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 52 of file igtlPolyDataMessage.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::PolyDataPointArray::ConstPointer
Definition at line 63 of file igtlPolyDataMessage.h.
typedef std::vector<igtlFloat32> igtl::PolyDataPointArray::Point
A vector to represent coordinates of a point.
Definition at line 57 of file igtlPolyDataMessage.h.
typedef SmartPointer<Self> igtl::PolyDataPointArray::Pointer
Definition at line 62 of file igtlPolyDataMessage.h.
typedef PolyDataPointArray igtl::PolyDataPointArray::Self
Definition at line 60 of file igtlPolyDataMessage.h.
typedef Object igtl::PolyDataPointArray::Superclass
Definition at line 61 of file igtlPolyDataMessage.h.
Constructor & Destructor Documentation
igtl::PolyDataPointArray::PolyDataPointArray () protected
igtl::PolyDataPointArray::~PolyDataPointArray () protected
Member Function Documentation
int igtl::PolyDataPointArray::AddPoint (igtlFloat32 * point)
Adds a point specified by 'point' to the list. The 'point' contains the x, y, and z coordinates of the point.
int igtl::PolyDataPointArray::AddPoint (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Adds a point 'point' specified by 'x', 'y' and 'z'.
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
void igtl::PolyDataPointArray::Clear ()
Clears the all points in the list.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
int igtl::PolyDataPointArray::GetNumberOfPoints ()
Gets the number of points in the list.
int igtl::PolyDataPointArray::GetPoint (unsigned int id, igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the coordinates of the point specified by 'id'.
int igtl::PolyDataPointArray::GetPoint (unsigned int id, igtlFloat32 * point)
Gets the coordinates of the point specified by 'id'.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::PolyDataPointArray::igtlNewMacro (igtl::PolyDataPointArray)
igtl::PolyDataPointArray::igtlTypeMacro (igtl::PolyDataPointArray , igtl::Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
void igtl::PolyDataPointArray::SetNumberOfPoints (int n)
Sets the number of points. This function will change the size of the list.
int igtl::PolyDataPointArray::SetPoint (unsigned int id, igtlFloat32 * point)
Substitutes the point specified by 'id' with a point specified by 'point'. The 'point' contains the x, y, and z coordinates of the point.
int igtl::PolyDataPointArray::SetPoint (unsigned int id, igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Substitutes the point specified by 'id' with a point specified by 'x', 'y' and 'z'.
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
The documentation for this class was generated from the following file:
igtlPolyDataMessage.h
Generated at Wed Sep 3 2014 08:12:39 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012