igtl::MutexLock Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::MutexLock Class Reference
#include <igtlMutexLock.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef MutexLock Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlNewMacro (Self)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (MutexLock, Object)
void Lock (void)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
virtual void SetReferenceCount (int)
void Unlock (void)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
MutexLock ()
void PrintSelf (std::ostream &os) const
~MutexLock ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
SimpleMutexLock m_SimpleMutexLock
Detailed Description
Mutual exclusion locking class.
MutexLock allows the locking of variables which are accessed through different threads. This header file also defines SimpleMutexLock which is not a subclass of igtlObject.
Definition at line 132 of file igtlMutexLock.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::MutexLock::ConstPointer
Definition at line 139 of file igtlMutexLock.h.
typedef SmartPointer<Self> igtl::MutexLock::Pointer
Definition at line 138 of file igtlMutexLock.h.
typedef MutexLock igtl::MutexLock::Self
Standard class typedefs.
Definition at line 136 of file igtlMutexLock.h.
typedef Object igtl::MutexLock::Superclass
Definition at line 137 of file igtlMutexLock.h.
Constructor & Destructor Documentation
igtl::MutexLock::MutexLock () inline protected
Definition at line 154 of file igtlMutexLock.h.
igtl::MutexLock::~MutexLock () inline protected
Definition at line 155 of file igtlMutexLock.h.
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::MutexLock::igtlNewMacro (Self)
Method for creation.
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
igtl::MutexLock::igtlTypeMacro (MutexLock , Object)
Run-time information.
void igtl::MutexLock::Lock (void) inline
Lock the igtlMutexLock.
Definition at line 166 of file igtlMutexLock.h.
References igtl::SimpleMutexLock::Lock(), and m_SimpleMutexLock.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
void igtl::MutexLock::PrintSelf (std::ostream & os) const protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::Object.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
void igtl::MutexLock::Unlock (void) inline
Unlock the MutexLock.
Definition at line 171 of file igtlMutexLock.h.
References m_SimpleMutexLock, and igtl::SimpleMutexLock::Unlock().
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
SimpleMutexLock igtl::MutexLock::m_SimpleMutexLock protected
Definition at line 157 of file igtlMutexLock.h.
Referenced by Lock(), and Unlock().
The documentation for this class was generated from the following file:
igtlMutexLock.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012