igtl::LabelMetaElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::LabelMetaElement Class Reference
#include <igtlLabelMetaMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LabelMetaElement Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
const char * GetDeviceName ()
igtlUint8 GetLabel ()
const char * GetName ()
virtual const char * GetNameOfClass () const
const char * GetOwner ()
virtual int GetReferenceCount () const
void GetRGBA (igtlUint8 *rgba)
void GetRGBA (igtlUint8 &r, igtlUint8 &g, igtlUint8 &b, igtlUint8 &a)
void GetSize (igtlUint16 *size)
void GetSize (igtlUint16 &si, igtlUint16 &sj, igtlUint16 &sk)
igtlNewMacro (igtl::LabelMetaElement)
igtlTypeMacro (igtl::LabelMetaElement, igtl::Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
int SetDeviceName (const char *devname)
void SetLabel (igtlUint8 label)
int SetName (const char *name)
int SetOwner (const char *owner)
virtual void SetReferenceCount (int)
void SetRGBA (igtlUint8 rgba[4])
void SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
void SetSize (igtlUint16 size[3])
void SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
LabelMetaElement ()
virtual void PrintSelf (std::ostream &os) const
~LabelMetaElement ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
std::string m_DeviceName
igtlUint8 m_Label
std::string m_Name
std::string m_Owner
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_RGBA [4]
igtlUint16 m_Size [3]
Detailed Description
Definition at line 31 of file igtlLabelMetaMessage.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::LabelMetaElement::ConstPointer
Definition at line 37 of file igtlLabelMetaMessage.h.
typedef SmartPointer<Self> igtl::LabelMetaElement::Pointer
Definition at line 36 of file igtlLabelMetaMessage.h.
typedef LabelMetaElement igtl::LabelMetaElement::Self
Definition at line 34 of file igtlLabelMetaMessage.h.
typedef Object igtl::LabelMetaElement::Superclass
Definition at line 35 of file igtlLabelMetaMessage.h.
Constructor & Destructor Documentation
igtl::LabelMetaElement::LabelMetaElement () protected
igtl::LabelMetaElement::~LabelMetaElement () protected
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
const char* igtl::LabelMetaElement::GetDeviceName () inline
Gets the device name (message name).
Definition at line 55 of file igtlLabelMetaMessage.h.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
igtlUint8 igtl::LabelMetaElement::GetLabel () inline
Gets the label of the structure.
Definition at line 61 of file igtlLabelMetaMessage.h.
const char* igtl::LabelMetaElement::GetName () inline
Gets the image name/description.
Definition at line 48 of file igtlLabelMetaMessage.h.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
const char* igtl::LabelMetaElement::GetOwner () inline
Gets the name of the image that owns this label map.
Definition at line 93 of file igtlLabelMetaMessage.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
void igtl::LabelMetaElement::GetRGBA (igtlUint8 * rgba)
Gets the color of the structure by an array representing RGBA.
void igtl::LabelMetaElement::GetRGBA (igtlUint8 & r, igtlUint8 & g, igtlUint8 & b, igtlUint8 & a)
Gets the color of the structure by R, G, B, and A values.
void igtl::LabelMetaElement::GetSize (igtlUint16 * size)
Gets the size of the image using an array containing the numbers of voxels in i, j, and k directions.
void igtl::LabelMetaElement::GetSize (igtlUint16 & si, igtlUint16 & sj, igtlUint16 & sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::LabelMetaElement::igtlNewMacro (igtl::LabelMetaElement)
igtl::LabelMetaElement::igtlTypeMacro (igtl::LabelMetaElement , igtl::Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
int igtl::LabelMetaElement::SetDeviceName (const char * devname)
Sets the device name (message name). The string 'devname' must not exceed 20 characters.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
void igtl::LabelMetaElement::SetLabel (igtlUint8 label) inline
Sets the label of the structure.
Definition at line 58 of file igtlLabelMetaMessage.h.
int igtl::LabelMetaElement::SetName (const char * name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
int igtl::LabelMetaElement::SetOwner (const char * owner)
Sets the name of the image that owns this label map.
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
void igtl::LabelMetaElement::SetRGBA (igtlUint8 rgba[4])
Sets the color of the structure by an array representing RGBA.
void igtl::LabelMetaElement::SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the structure by R, G, B, and A values.
void igtl::LabelMetaElement::SetSize (igtlUint16 size[3])
Sets the size of the image by an array containing the numbers of voxels in i, j, and k directions.
void igtl::LabelMetaElement::SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
std::string igtl::LabelMetaElement::m_DeviceName protected
Device name to query the IMAGE and COLORT.
Definition at line 105 of file igtlLabelMetaMessage.h.
igtlUint8 igtl::LabelMetaElement::m_Label protected
Label.
Definition at line 108 of file igtlLabelMetaMessage.h.
std::string igtl::LabelMetaElement::m_Name protected
Name / description (<= 64 bytes)
Definition at line 102 of file igtlLabelMetaMessage.h.
std::string igtl::LabelMetaElement::m_Owner protected
device name of the owner image. (can be empty)
Definition at line 117 of file igtlLabelMetaMessage.h.
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
igtlUint8 igtl::LabelMetaElement::m_RGBA[4] protected
Color in RGBA. default: (0, 0, 0, 0)
Definition at line 111 of file igtlLabelMetaMessage.h.
igtlUint16 igtl::LabelMetaElement::m_Size[3] protected
entire image volume size
Definition at line 114 of file igtlLabelMetaMessage.h.
The documentation for this class was generated from the following file:
igtlLabelMetaMessage.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012