igtl::SessionManager Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::SessionManager Class Reference
#include <igtlSessionManager.h>
Public Types
enum {
MODE_SERVER,
MODE_CLIENT
}
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef SessionManager Self
typedef Object Superclass
Public Member Functions
int AddMessageHandler (MessageHandler *)
int Connect ()
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int Disconnect ()
bool GetDebug () const
const char * GetHostname ()
int GetMode ()
virtual const char * GetNameOfClass () const
int GetPort ()
virtual int GetReferenceCount () const
igtlTypeMacro (SessionManager, Object) igtlNewMacro(SessionManager)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
int ProcessMessage ()
int PushMessage (MessageBase *)
virtual void Register () const
int RemoveMessageHandler (MessageHandler *)
void SetDebug (bool debugFlag) const
void SetHostname (const char *str)
void SetMode (int m)
void SetPort (int p)
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
virtual void PrintSelf (std::ostream &os) const
SessionManager ()
~SessionManager ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
bool m_ConfigurationUpdated
MessageHandler * m_CurrentMessageHandler
int m_CurrentReadIndex
igtl::MessageHeader::Pointer m_Header
int m_HeaderDeserialized
std::string m_Hostname
std::vector< MessageHandler * > m_MessageHandlerList
int m_Mode
int m_Port
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Socket::Pointer m_Socket
igtl::TimeStamp::Pointer m_TimeStamp
Detailed Description
Definition at line 28 of file igtlSessionManager.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::SessionManager::ConstPointer
Definition at line 35 of file igtlSessionManager.h.
typedef SmartPointer<Self> igtl::SessionManager::Pointer
Definition at line 34 of file igtlSessionManager.h.
typedef SessionManager igtl::SessionManager::Self
Definition at line 32 of file igtlSessionManager.h.
typedef Object igtl::SessionManager::Superclass
Definition at line 33 of file igtlSessionManager.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MODE_SERVER
MODE_CLIENT
Definition at line 41 of file igtlSessionManager.h.
Constructor & Destructor Documentation
igtl::SessionManager::SessionManager () protected
igtl::SessionManager::~SessionManager () protected
Member Function Documentation
int igtl::SessionManager::AddMessageHandler (MessageHandler *)
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
int igtl::SessionManager::Connect ()
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
int igtl::SessionManager::Disconnect ()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
const char* igtl::SessionManager::GetHostname () inline
Definition at line 47 of file igtlSessionManager.h.
int igtl::SessionManager::GetMode () inline
Definition at line 54 of file igtlSessionManager.h.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
int igtl::SessionManager::GetPort () inline
Definition at line 49 of file igtlSessionManager.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::SessionManager::igtlTypeMacro (SessionManager , Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
int igtl::SessionManager::ProcessMessage ()
int igtl::SessionManager::PushMessage (MessageBase *)
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
int igtl::SessionManager::RemoveMessageHandler (MessageHandler *)
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
void igtl::SessionManager::SetHostname (const char * str) inline
Definition at line 46 of file igtlSessionManager.h.
void igtl::SessionManager::SetMode (int m) inline
Definition at line 53 of file igtlSessionManager.h.
void igtl::SessionManager::SetPort (int p) inline
Definition at line 48 of file igtlSessionManager.h.
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
bool igtl::SessionManager::m_ConfigurationUpdated protected
Definition at line 73 of file igtlSessionManager.h.
MessageHandler* igtl::SessionManager::m_CurrentMessageHandler protected
Definition at line 85 of file igtlSessionManager.h.
int igtl::SessionManager::m_CurrentReadIndex protected
Definition at line 82 of file igtlSessionManager.h.
igtl::MessageHeader::Pointer igtl::SessionManager::m_Header protected
Definition at line 90 of file igtlSessionManager.h.
int igtl::SessionManager::m_HeaderDeserialized protected
Definition at line 83 of file igtlSessionManager.h.
std::string igtl::SessionManager::m_Hostname protected
Definition at line 74 of file igtlSessionManager.h.
std::vector< MessageHandler* > igtl::SessionManager::m_MessageHandlerList protected
Definition at line 87 of file igtlSessionManager.h.
int igtl::SessionManager::m_Mode protected
Definition at line 76 of file igtlSessionManager.h.
int igtl::SessionManager::m_Port protected
Definition at line 75 of file igtlSessionManager.h.
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
Socket::Pointer igtl::SessionManager::m_Socket protected
Definition at line 88 of file igtlSessionManager.h.
igtl::TimeStamp::Pointer igtl::SessionManager::m_TimeStamp protected
Definition at line 91 of file igtlSessionManager.h.
The documentation for this class was generated from the following file:
igtlSessionManager.h
Generated at Wed Sep 3 2014 08:12:39 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012