igtl::MultiThreader Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::MultiThreader Class Reference
#include <igtlMultiThreader.h>
Classes
class ThreadInfo
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef MultiThreader Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetNumberOfThreads ()
virtual int GetReferenceCount () const
igtlNewMacro (Self)
igtlSetClampMacro (NumberOfThreads, int, 1, IGTL_MAX_THREADS)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (MultiThreader, Object)
void MultipleMethodExecute ()
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
void SetMultipleMethod (int index, ThreadFunctionType, void *data)
virtual void SetReferenceCount (int)
void SetSingleMethod (ThreadFunctionType, void *data)
void SingleMethodExecute ()
int SpawnThread (ThreadFunctionType, void *data)
void TerminateThread (int thread_id)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static MultiThreaderIDType GetCurrentThreadID ()
static int GetGlobalDefaultNumberOfThreads ()
static int GetGlobalMaximumNumberOfThreads ()
static Pointer New ()
static void SetGlobalDefaultNumberOfThreads (int val)
static void SetGlobalMaximumNumberOfThreads (int val)
static int ThreadsEqual (MultiThreaderIDType t1, MultiThreaderIDType t2)
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
MultiThreader ()
void PrintSelf (std::ostream &os) const
~MultiThreader ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
void * m_MultipleData [IGTL_MAX_THREADS]
ThreadFunctionType m_MultipleMethod [IGTL_MAX_THREADS]
int m_NumberOfThreads
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
void * m_SingleData
ThreadFunctionType m_SingleMethod
int m_SpawnedThreadActiveFlag [IGTL_MAX_THREADS]
MutexLock::Pointer m_SpawnedThreadActiveFlagLock [IGTL_MAX_THREADS]
ThreadInfo m_SpawnedThreadInfoArray [IGTL_MAX_THREADS]
ThreadProcessIDType m_SpawnedThreadProcessID [IGTL_MAX_THREADS]
ThreadInfo m_ThreadInfoArray [IGTL_MAX_THREADS]
Detailed Description
Definition at line 132 of file igtlMultiThreader.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::MultiThreader::ConstPointer
Definition at line 139 of file igtlMultiThreader.h.
typedef SmartPointer<Self> igtl::MultiThreader::Pointer
Definition at line 138 of file igtlMultiThreader.h.
typedef MultiThreader igtl::MultiThreader::Self
Standard class typedefs.
Definition at line 136 of file igtlMultiThreader.h.
typedef Object igtl::MultiThreader::Superclass
Definition at line 137 of file igtlMultiThreader.h.
Constructor & Destructor Documentation
igtl::MultiThreader::MultiThreader () protected
igtl::MultiThreader::~MultiThreader () protected
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
static MultiThreaderIDType igtl::MultiThreader::GetCurrentThreadID () static
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static int igtl::MultiThreader::GetGlobalDefaultNumberOfThreads () static
static int igtl::MultiThreader::GetGlobalMaximumNumberOfThreads () static
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
virtual int igtl::MultiThreader::GetNumberOfThreads () virtual
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::MultiThreader::igtlNewMacro (Self)
igtl::MultiThreader::igtlSetClampMacro (NumberOfThreads , int , 1 , IGTL_MAX_THREADS)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
igtl::MultiThreader::igtlTypeMacro (MultiThreader , Object)
void igtl::MultiThreader::MultipleMethodExecute ()
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
void igtl::MultiThreader::PrintSelf (std::ostream & os) const protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::Object.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::MultiThreader::SetGlobalDefaultNumberOfThreads (int val) static
static void igtl::MultiThreader::SetGlobalMaximumNumberOfThreads (int val) static
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
void igtl::MultiThreader::SetMultipleMethod (int index, ThreadFunctionType , void * data)
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
void igtl::MultiThreader::SetSingleMethod (ThreadFunctionType , void * data)
void igtl::MultiThreader::SingleMethodExecute ()
int igtl::MultiThreader::SpawnThread (ThreadFunctionType , void * data)
void igtl::MultiThreader::TerminateThread (int thread_id)
static int igtl::MultiThreader::ThreadsEqual (MultiThreaderIDType t1, MultiThreaderIDType t2) static
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
void* igtl::MultiThreader::m_MultipleData[IGTL_MAX_THREADS] protected
Definition at line 267 of file igtlMultiThreader.h.
ThreadFunctionType igtl::MultiThreader::m_MultipleMethod[IGTL_MAX_THREADS] protected
Definition at line 254 of file igtlMultiThreader.h.
int igtl::MultiThreader::m_NumberOfThreads protected
Definition at line 245 of file igtlMultiThreader.h.
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
void* igtl::MultiThreader::m_SingleData protected
Definition at line 266 of file igtlMultiThreader.h.
ThreadFunctionType igtl::MultiThreader::m_SingleMethod protected
Definition at line 253 of file igtlMultiThreader.h.
int igtl::MultiThreader::m_SpawnedThreadActiveFlag[IGTL_MAX_THREADS] protected
Definition at line 258 of file igtlMultiThreader.h.
MutexLock::Pointer igtl::MultiThreader::m_SpawnedThreadActiveFlagLock[IGTL_MAX_THREADS] protected
Definition at line 259 of file igtlMultiThreader.h.
ThreadInfo igtl::MultiThreader::m_SpawnedThreadInfoArray[IGTL_MAX_THREADS] protected
Definition at line 261 of file igtlMultiThreader.h.
ThreadProcessIDType igtl::MultiThreader::m_SpawnedThreadProcessID[IGTL_MAX_THREADS] protected
Definition at line 260 of file igtlMultiThreader.h.
ThreadInfo igtl::MultiThreader::m_ThreadInfoArray[IGTL_MAX_THREADS] protected
Definition at line 250 of file igtlMultiThreader.h.
The documentation for this class was generated from the following file:
igtlMultiThreader.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012