igtl::ObjectFactory< T > Class Template Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::ObjectFactory< T > Class Template Reference abstract
#include <igtlObjectFactory.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef ObjectFactoryBase Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
virtual void Disable (const char *className)
virtual std::list< std::string > GetClassOverrideDescriptions ()
virtual std::list< std::string > GetClassOverrideNames ()
virtual std::list< std::string > GetClassOverrideWithNames ()
bool GetDebug () const
virtual const char * GetDescription (void) const =0
virtual bool GetEnableFlag (const char *className, const char *subclassName)
virtual std::list< bool > GetEnableFlags ()
virtual const char * GetIGTLSourceVersion (void) const =0
const char * GetLibraryPath ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlTypeMacro (ObjectFactoryBase, Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
virtual void SetEnableFlag (bool flag, const char *className, const char *subclassName)
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static T::Pointer Create ()
static std::list
< LightObject::Pointer > CreateAllInstance (const char *igtlclassname)
static LightObject::Pointer CreateInstance (const char *igtlclassname)
static std::list
< ObjectFactoryBase * > GetRegisteredFactories ()
static Pointer New ()
static void RegisterFactory (ObjectFactoryBase *)
static void ReHash ()
static void UnRegisterAllFactories ()
static void UnRegisterFactory (ObjectFactoryBase *)
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
virtual LightObject::Pointer CreateObject (const char *igtlclassname)
virtual void PrintSelf (std::ostream &os) const
void RegisterOverride (const char *classOverride, const char *overrideClassName, const char *description, bool enableFlag, CreateObjectFunctionBase *createFunction)
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
template<class T>
class igtl::ObjectFactory< T >
Create instances of a class.
ObjectFactory is a helper class used to created instances of a class. Object factories are used for instantiation because they allow run-time replacement of a class with a user-supplied version. For example, if you wished to replace an algorithm with your own custom version, or with a hardware-accelerated version, ObjectFactory can be used to do this.
This implementation of the object factory is templated and uses RTTI (Run-Time Type Information) to create the name of the class it is to instantiate. (The name may include template type parameters, depending on the class definition.)
Definition at line 60 of file igtlObjectFactory.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::ObjectFactoryBase::ConstPointer inherited
Definition at line 70 of file igtlObjectFactoryBase.h.
typedef SmartPointer<Self> igtl::ObjectFactoryBase::Pointer inherited
Definition at line 69 of file igtlObjectFactoryBase.h.
typedef ObjectFactoryBase igtl::ObjectFactoryBase::Self inherited
Standard class typedefs.
Definition at line 67 of file igtlObjectFactoryBase.h.
typedef Object igtl::ObjectFactoryBase::Superclass inherited
Definition at line 68 of file igtlObjectFactoryBase.h.
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
template<class T > static T::Pointer igtl::ObjectFactory< T >::Create () inline static
Definition at line 63 of file igtlObjectFactory.h.
References igtl::ObjectFactoryBase::CreateInstance(), and igtl::SmartPointer< TObjectType >::GetPointer().
static std::list<LightObject::Pointer> igtl::ObjectFactoryBase::CreateAllInstance (const char * igtlclassname) static inherited
Create and return all possible instances of the named igtl object. Each loaded ObjectFactoryBase will be asked in the order the factory was in the IGTL_AUTOLOAD_PATH. All created objects will be returned in the list.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
static LightObject::Pointer igtl::ObjectFactoryBase::CreateInstance (const char * igtlclassname) static inherited
Create and return an instance of the named igtl object. Each loaded ObjectFactoryBase will be asked in the order the factory was in the IGTL_AUTOLOAD_PATH. After the first factory returns the object no other factories are asked.
Referenced by igtl::ObjectFactory< T >::Create().
virtual LightObject::Pointer igtl::ObjectFactoryBase::CreateObject (const char * igtlclassname) protected virtual inherited
This method is provided by sub-classes of ObjectFactoryBase. It should create the named igtl object or return 0 if that object is not supported by the factory implementation.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
virtual void igtl::ObjectFactoryBase::Disable (const char * className) virtual inherited
Set all enable flags for the given class to 0. This will mean that the factory will stop producing class with the given name.
virtual std::list<std::string> igtl::ObjectFactoryBase::GetClassOverrideDescriptions () virtual inherited
Return a list of descriptions for class overrides.
virtual std::list<std::string> igtl::ObjectFactoryBase::GetClassOverrideNames () virtual inherited
Return a list of classes that this factory overrides.
virtual std::list<std::string> igtl::ObjectFactoryBase::GetClassOverrideWithNames () virtual inherited
Return a list of the names of classes that override classes.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
virtual const char* igtl::ObjectFactoryBase::GetDescription (void) const pure virtual inherited
Return a descriptive string describing the factory.
virtual bool igtl::ObjectFactoryBase::GetEnableFlag (const char * className, const char * subclassName) virtual inherited
Get the Enable flag for the specific override of className.
virtual std::list<bool> igtl::ObjectFactoryBase::GetEnableFlags () virtual inherited
Return a list of enable flags.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
virtual const char* igtl::ObjectFactoryBase::GetIGTLSourceVersion (void) const pure virtual inherited
All sub-classes of ObjectFactoryBase should must return the version of IGTL they were built with. This should be implemented with the macro IGTL_SOURCE_VERSION and NOT a call to Version::GetIGTLSourceVersion. As the version needs to be compiled into the file as a string constant. This is critical to determine possible incompatible dynamic factory loads.
const char* igtl::ObjectFactoryBase::GetLibraryPath () inherited
This returns the path to a dynamically loaded factory.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static std::list<ObjectFactoryBase*> igtl::ObjectFactoryBase::GetRegisteredFactories () static inherited
Return the list of all registered factories. This is NOT a copy, do not remove items from this list!
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::ObjectFactoryBase::igtlTypeMacro (ObjectFactoryBase , Object) inherited
Run-time type information (and related methods).
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::ObjectFactoryBase::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::Object.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
static void igtl::ObjectFactoryBase::RegisterFactory (ObjectFactoryBase *) static inherited
Register a factory so it can be used to create igtl objects.
void igtl::ObjectFactoryBase::RegisterOverride (const char * classOverride, const char * overrideClassName, const char * description, bool enableFlag, CreateObjectFunctionBase * createFunction) protected inherited
Register object creation information with the factory.
static void igtl::ObjectFactoryBase::ReHash () static inherited
Re-check the IGTL_AUTOLOAD_PATH for new factory libraries. This calls UnRegisterAll before re-loading.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
virtual void igtl::ObjectFactoryBase::SetEnableFlag (bool flag, const char * className, const char * subclassName) virtual inherited
Set the Enable flag for the specific override of className.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
static void igtl::ObjectFactoryBase::UnRegisterAllFactories () static inherited
Unregister all factories.
static void igtl::ObjectFactoryBase::UnRegisterFactory (ObjectFactoryBase *) static inherited
Remove a factory from the list of registered factories.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
The documentation for this class was generated from the following file:
igtlObjectFactory.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012