igtl::MessageFactory Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::MessageFactory Class Reference
#include <igtlMessageFactory.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef MessageFactory Self
typedef Object Superclass
Public Member Functions
virtual LightObject::Pointer CreateAnother () const
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
igtl::MessageBase::Pointer GetMessage (igtl::MessageHeader::Pointer headerMsg)
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlTypeMacro (MessageFactory, Object) igtlNewMacro(MessageFactory)
igtlTypeMacro (Object, LightObject)
bool IsValid (igtl::MessageHeader::Pointer headerMsg)
void Print (std::ostream &os) const
virtual void Register () const
void SetDebug (bool debugFlag) const
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
Protected Member Functions
MessageFactory ()
virtual void PrintSelf (std::ostream &os) const
~MessageFactory ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 27 of file igtlMessageFactory.h.
Member Typedef Documentation
typedef SmartPointer<const Self> igtl::MessageFactory::ConstPointer
Definition at line 35 of file igtlMessageFactory.h.
typedef SmartPointer<Self> igtl::MessageFactory::Pointer
Definition at line 34 of file igtlMessageFactory.h.
typedef MessageFactory igtl::MessageFactory::Self
Definition at line 32 of file igtlMessageFactory.h.
typedef Object igtl::MessageFactory::Superclass
Definition at line 33 of file igtlMessageFactory.h.
Constructor & Destructor Documentation
igtl::MessageFactory::MessageFactory () protected
igtl::MessageFactory::~MessageFactory () protected
Member Function Documentation
static void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
virtual LightObject::Pointer igtl::Object::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
virtual void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
virtual void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
virtual void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
static bool igtl::Object::GetGlobalWarningDisplay () static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
igtl::MessageBase::Pointer igtl::MessageFactory::GetMessage (igtl::MessageHeader::Pointer headerMsg)
Constructs a message from the given header. Throws invalid_argument if headerMsg is NULL. Throws invalid_argument if this->IsValid(headerMsg) returns false. Creates message, sets header onto message and calls AllocatePack() on the message.
virtual const char* igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 110 of file igtlLightObject.h.
static void igtl::Object::GlobalWarningDisplayOff () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 116 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
static void igtl::Object::GlobalWarningDisplayOn () inline static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Definition at line 114 of file igtlObject.h.
References igtl::Object::SetGlobalWarningDisplay().
igtl::MessageFactory::igtlTypeMacro (MessageFactory , Object)
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
bool igtl::MessageFactory::IsValid (igtl::MessageHeader::Pointer headerMsg)
Checks that headerMsg is not null and the headerMsg->GetDeviceType() refers to a valid type, returning true if valid, and false otherwise.
static Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
virtual void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::Socket, igtl::FastMutexLock, igtl::TimeStamp, igtl::ServerSocket, and igtl::ClientSocket.
virtual void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
virtual void igtl::Object::Register () const virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
static void igtl::Object::SetGlobalWarningDisplay (bool flag) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Referenced by igtl::Object::GlobalWarningDisplayOff(), and igtl::Object::GlobalWarningDisplayOn().
virtual void igtl::Object::SetReferenceCount (int) virtual inherited
Sets the reference count (use with care)
Reimplemented from igtl::LightObject.
virtual void igtl::Object::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented from igtl::LightObject.
Member Data Documentation
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 131 of file igtlLightObject.h.
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 134 of file igtlLightObject.h.
The documentation for this class was generated from the following file:
igtlMessageFactory.h
Generated at Wed Sep 3 2014 08:12:38 for OpenIGTLink by 1.8.8 written by Dimitri van Heesch, © 1997-2012